#------------------------------------------------------------------------------

SOURCE=*.cpp
MYPROGRAM=test

CC=g++

#------------------------------------------------------------------------------



all: $(MYPROGRAM)



$(MYPROGRAM): $(SOURCE)

	$(CC) -O2 -lm $(SOURCE) -o$(MYPROGRAM) 

clean:

	rm -f $(MYPROGRAM)
